### ISSUE TITLE
Remove or otherwise disambiguate the old draft OFCIO IT Modernization policy

### ISSUE THREAD

**Issue by konklone** [ombegov/policy-v2#103]
I saw this get mistakenly sent out to a large list of government staff as the president's IT Modernization report:

https://policy.cio.gov/it-modernization/

I think it'd be good to take it down (since it was draft and never issued), or at the least, clearly disambiguate it and link to the new one.

cc @rebeccawilliams @mattbailey0 (also h/t to @rebeccawilliams for noting this at https://github.com/GSA/modernization/issues/6)

**Comment by Thomas-Romanoff** [comment]
Hi Eric
Thank you for the flag.  This site is scheduled to go through a general clean up and we will prioritize your concern.

Tom

**Comment by konklone** [comment]
@Thomas-Romanoff @mattbailey0 OK, thanks. As the maintainer of the IT Modernization report website/repo, and watching significant confusion be generated, I appreciate the priority, and so I went and filed a PR that removes it for now:

https://github.com/ombegov/policy-v2/pull/104

I tested it out locally, and searched for other references to the draft policy and couldn't find any. It causes the existing page to 404. I suggest merging it as an interim step before adding redirects or restoring it in a disambiguated form.

**Comment by mattbailey0** [comment]
@konklone sorry for the confusion. @Thomas-Romanoff please have the team pull this down sooner rather than later. I suggest leaving the page in place but replacing the content with an message directing people to the finalized report.

**Comment by Thomas-Romanoff** [comment]
@konklone @mattbailey0 The page has been updated and directs anyone looking for the IT Mod report to the GSA page.

**Comment by konklone** [comment]
Thanks, @Thomas-Romanoff!

There's a small typo though:

> This is a separate initiative then what was listed on this site. 

The `then` isn't right. It could be `than`, but it would read best as:

> This is a separate initiative from what was listed on this site.
