### ISSUE TITLE
Inconsistent Guidance on DCOI Strategic Plan Schema

### ISSUE THREAD

**Issue by djharrity** [ombegov/policy-v2#108]
The DCOI Strategic Plan Schema presented at https://policy.cio.gov/fitara-resources/schema/ is not the same schema presented for the DCOI Strategic Plan Schema at https://management.cio.gov/schema/

More specifically, the last entry of "lifecycleCostSavingsEstimated" for https://policy.cio.gov/fitara-resources/schema/ has been replaced with "historicalCostSavings".

GAO reports focus on "historicalCostSavings" as reflected by finding statements such as, "GAO also identified inconsistencies in how 11 agencies reported historical cost savings in their DCOI strategic plans, as compared to a separate required quarterly report to OMB."

This has resulted in at least one agency mistakenly using the lifecycleCostSavingsEstimated entry.

Request:
1. Request that the https://policy.cio.gov/fitara-resources/schema/ page be updated to be consistent with https://management.cio.gov/schema/ -- Or, removed in its entirety and details on the schema be listed at only one location.

2. Lastly, recommend that https://management.cio.gov/schema/ is updated to include "fy17Achieved" values in each area, as appropriate.

**Comment by mattbailey0** [comment]
Thanks @djharrity - looking into this.

**Comment by Thomas-Romanoff** [comment]
fixed the schema.
