### ISSUE TITLE
Broken link in M-17-06

### ISSUE THREAD

**Issue by h-m-f-t** [ombegov/policy-v2#221]
M-17-06 instructs agencies to report their use of non-.gov/.mil domains, but the link in [§9(D)](https://policy.cio.gov/web-policy/domain/) (pointing to http://search.digitalgov.gov/developer/govt-urls.html) 404's. I think the correct URL may be https://govt-urls.usa.gov/tematres/vocab/index.php.

Collecting this data centrally can be very helpful for multiple purposes; mine is in light of e.g., CISA's [Emergency Directive 19-01](https://cyber.dhs.gov/ed/19-01/#action-one-audit-dns-records).

It could be helpful to provide agencies with a bit more info on how they actually update the collection. Perhaps this can be included at the landing URL.

cc: @dawnpm @jsf9k @climber-girl @tdlowden

**Comment by thecapacity** [comment]
CC @jeremyzilar I think you might have some thoughts on the URL updating - seems easier for GSA to fix the URL than OMB to update the policy

**Comment by dawnpm** [comment]
The page referenced was removed last June (in addition to the domain change from search.digitalgov.gov to search.gov). The link @h-m-f-t provided is correct. Would it also be possible to list the contact information for the Search.gov team, so folks will know whom to reach out to with updates?

**Comment by h-m-f-t** [comment]
For clarity, my comment about "a bit more info" is probably more targeted to the _destination link_ in the web policy than for the web policy itself. (Currently there's no guidance there to help users submit domains.)

**Comment by dawnpm** [comment]
You make a good point, I’ll put a page back up with instructions, and will loop back here with the correct link. More soon.

**Comment by dawnpm** [comment]
This issue can be closed, https://search.gov/developer/govt-urls.html has been restored, and now includes better instructions on how to review and update the list.

**Comment by h-m-f-t** [comment]
Thanks @dawnpm!

**Comment by jeremyzilar** [comment]
Thanks all!
