### ISSUE TITLE
Cross Walking the Schema to Legislation and Regulation 

### ISSUE THREAD

**Issue by Thomas-Romanoff** [ombegov/policy-v2#27]
A distant goal for this project is to create a schema that is interoperable with USLM and NARA schemas.  Is this possible and how would we do it?

**Comment by konklone** [comment]
cc @cmc333333

**Comment by citizencontact** [comment]
There are two issues I see. 

The first and most important is how to reference other documents in other schemas. I would look to electronic citations. You should be able to reference any portion of a document through either an electronic citation, a URL with fragment/#id or an XPath statement. Note that a citation could include the metadata, for example Dublin Core or MODS.

The second is whether to try to create an XSLT between them which would be troublesome and hard to version. I suggest instead using an HTML5 method of mixing them using Microdata and/or RDFa. See: 

- `https://github.com/tfrancart/schemaorg`
- `https://github.com/schemaorg/schemaorg/issues/1156`
