### ISSUE TITLE
Discussion Archives: Improving Cybersecurity Protections in Federal Acquisitions

### ISSUE THREAD

**Issue by mattbailey0** [ombegov/policy-v2#38]
Historical discussion on the draft memorandum on Improving Cybersecurity Protection in Federal Acquisitions [can be found here](https://github.com/WhiteHouse/cyber-acquisitions/issues).

**Comment by pmerrion** [comment]
When was this draft memorandum posted?

**Comment by Thomas-Romanoff** [comment]
@pmerrion the draft memorandum comment period was closed Sept 11, 2015.  Usually the draft memorandum is posted 30 days before the closing.  The memo was posted  roughly around August 9, 2015
