### ISSUE TITLE
Bug Hunting 

### ISSUE THREAD

**Issue by Thomas-Romanoff** [ombegov/policy-v2#45]
This is what I have found so far-
https://policy.cio.gov/fitara/
-	No side bar drop down menu for M-15-14
-	Formatting is different between the policies 
https://policy.cio.gov/cybersecurity-protections-in-federal-acquisitions/
-	No sidebar drop down menu
https://policy.cio.gov/resources/
-	Needs more content
-	Might be a good place for schema

**Comment by mattbailey0** [comment]
could you open these as individual issues?

**Comment by Thomas-Romanoff** [comment]
sure no problem
