### ISSUE TITLE
M-13-13

### ISSUE THREAD

**Issue by TheLastQuestion** [ombegov/policy-v2#49]
Thought i'd made a pull request dropping m-13-13 text in markdown...but don't see it. Were there issues?

**Comment by mattbailey0** [comment]
@Thomas-Romanoff can you help Bryant with this?

**Comment by Thomas-Romanoff** [comment]
@TheLastQuestion did everything work?

**Comment by TheLastQuestion** [comment]
looks good in the github repo, but m-13-13 directory/pages doesnt exist on actual page (yet).

does a refresh need to happen...?

also, will compiler create left-hand menu option automatically? or do i need to add code...?

**Comment by Thomas-Romanoff** [comment]
It should do it automatically.  The config file needs to be updated for it to show up on the page @mattbailey0 do you want me to update the master config with M-13-13?

**Comment by TheLastQuestion** [comment]
just added m-13-13 into config yaml file as a pull request

**Comment by TheLastQuestion** [comment]
the footnotes.md file in the m-13-13 directory should be removed/deleted, as I have now added them into the footer of their respective sections of the policy (intro, scope, policy requirements, etc.). Having them as a separate section at the end of the policy memo is redundant.
