### ISSUE TITLE
IT Modernization Comment Period - Welcome!

### ISSUE THREAD

**Issue by mattbailey0** [ombegov/policy-v2#64]
The Office of Management and Budget (OMB) is proposing a new policy to modernize the Federal government's aging IT systems. This memorandum would require the CFO-Act agencies to identify systems as candidates for modernization and submit modernization proposals to OMB. Research and agency-submitted analysis indicates that aging legacy systems pose operations risks for the agencies and the government as a whole when these systems cannot adapt to current or expected mission requirements, user needs, or operating environments. This memorandum strives to assist agencies with the costs and risks of modernizing critical systems, and it seeks to promote cost reductions, risk reductions, and improved delivery of services to the American public through modernization of these systems. Authority for this notice is granted under the Clinger-Cohen Act, 40 U.S.C. Subtitle III.

The 30-day public comment period on the draft memorandum begins on October 26, 2016 in and will last for 30 days. The public comment period will end on November 25, 2016.

You can comment by opening an issue or pull request here or via the [Federal Register](https://www.federalregister.gov/documents/2016/10/27/2016-25948/request-for-comments-on-information-technology-modernization-initiative). 

[Check out the draft policy here](https://policy.cio.gov/it-modernization/)

**Comment by cioportfolio** [comment]
Most (arguable all) IT systems are components within a larger operational system and tightly integrated with policy, manual activities and other elements. It should be made clearer that IT modernisation cannot be carried out in isolation and the plans and roadmaps for IT need to be developed as an element of plans to modernise whole public services.

**Comment by cioportfolio** [comment]
IT modernization is a tactical response to issues created due to poor IT portfolio management. If this is not tackled at the same time today's modernized IT will just be the source of tomorrow's high risk legacy IT. Roadmaps and long range planning can form a part of good practice but needs to be supported but changes to governance and funding practices.

**Comment by cioportfolio** [comment]
What modelling had been done to look at a healthy ratio between spending on "new" IT and "legacy" IT? If existing IT is well managed and delivering good value why shouldn't it attract a large share of IT spending?

**Comment by rgdeluca** [comment]
Strongly agree a policy this like is needed. However, small agencies, which tend to have much more restricted IT budgets than the large CFO Act agencies, need to be included (with special exceptions and/or set asides) and gain access to the ITMF funding to enable their CIOs to make the same advancements. Knowing the limited resources available to smaller agencies, requirements such as a minimum of 3 submissions to OMB, may be too burdensome; the approach, criteria, and execution could still be applicable and highly impactful to the small agencies’ missions.

**Comment by rebeccawilliams** [comment]
Comment period closed ended on November 25, 2016 (according to the above) and according to: https://policy.cio.gov/it-modernization/. Was a finalized memo ever issued? If not should there be a section for drafts that were never finalized on policy.cio.gov? (I think there should be)

Recently a new comment period has been opened for the IT modernization initiative until September 20, 2017 according to: https://www.whitehouse.gov/blog/2017/08/30/it-modernization and https://itmodernization.cio.gov/ (a site running from a GSA repo). How is this initiative different and how is this comment period different?
