### ISSUE TITLE
Document Download Incorrect

### ISSUE THREAD

**Issue by anjelicad** [ombegov/policy-v2#86]
The DCOI document download provides the wrong memorandum. It currently downloads M-13-13 Open Data Policy instead of M-16-19 DCOI.

**Comment by Thomas-Romanoff** [comment]
@mattbailey0 I fixed the link, should i go ahead merge with master?

**Comment by mattbailey0** [comment]
@anjelicad, a year later, I'm assuming you meant the link at https://policy.cio.gov/dcoi/, which now works. Closing this issue but feel free to reopen and clarify if I misinterpreted!
